config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  devise_for :users
  resources :items
  resource :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    Item.create!(name: item_params[:name], price: item_params[:price], user_id: current_user.id)
  end

  private
  def item_params
    params.require(:item).permit(:name, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @items = current_user.items
  end

  def create
    current_user.items.create!(item_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>投稿が完了しました</h1>
<%= link_to '投稿一覧へ戻る', items_path %>

app/views/items/index.html.erb
<h1>購入商品一覧</h1>
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <p><%= item.name %> : <%= item.price %> : <%= item.user.nickname.present? ? "購入者 #{item.user.nickname}" : "会員No. #{item.user.id}" %></p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/items/new.html.erb
<h1>ご購入商品の情報を入力</h1>
<%= form_with model: @item, local: true do |form|  %>
  <p><%= form.label :name, "商品名" %> <%= form.text_field :name %></p>
  <p><%= form.label :price, "値段" %> <%= form.text_field :price %></p>
  <%= form.submit "送信" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <!-- ログイン時 -->
      <%= link_to "トップ",items_path %>
      <%= link_to '投稿画面へ', new_item_path %>
      <%= link_to 'マイページへ', users_path %>
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
    <% else %>
       <!-- 非ログイン時 -->
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "アカウント登録", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% @items.each do |item| %>
  <p><%= item.name %> : <%= item.price %></p>
<% end %>